### ISSUE TITLE
position: center

### ISSUE THREAD

**Issue by Riclim** [dgknca/simple-notify#1]
Thank you for it! Would be possible to add 'center' to position?

**Comment by dgknca** [comment]
🔥🔥 Now you can use `position: 'center'` to center both x and y axis. Or you can combine `y-center` with `left` or `right` and `x-center` with `top` or `bottom`.

- `'center'`
- `'x-center top'`
- `'x-center bottom'`
- `'y-center left'`
- `'y-center right'`
