### ISSUE TITLE
Add 'info' status with blue color

### ISSUE THREAD

**Issue by dgknca** [dgknca/simple-notify#9]

**Comment by pavankalyan-codes** [comment]
Hey! I want to work on this. Can you pls assign this to me.

**Comment by dgknca** [comment]
> is there a specific icon you would like for the 'info' status?

you can use one of the available icons. I'll design it later.

**Comment by dgknca** [comment]
> Hey! I want to work on this. Can you pls assign this to me.

there is 2 people here, but I think I can merge your all PRs. I won't assign it to a specific person but you can work on it. your efforts will not be in vain. even though, you can choose another issue or or you can add a feature you want if you want. Or you can make a refactoring. It is not must to just go through the issues. they are all welcomed 🚀

**Comment by pavankalyan-codes** [comment]
> > Hey! I want to work on this. Can you pls assign this to me.
> 
> there is 2 people here, but I think I can merge your all PRs. I won't assign it to a specific person but you can work on it. your efforts will not be in vain. even though, you can choose another issue or or you can add a feature you want if you want. Or you can make a refactoring. It is not must to just go through the issues. they are all welcomed 🚀

Hey! made a PR for this. pls review and suggest if any more changes are required. If everything looks fine on review pls merge it. #24
